version: '3'

tasks:

  doc:run:
    desc: Run documentation locally
    cmds:
      - |
        docker run \
          --pull always \
          --rm \
          -p 8000:8000 \
          -v ${PWD}/seeder-doc:/docs \
          squidfunk/mkdocs-material

  image:build:
    desc: Build Docker image
    cmds:
      - docker build --tag ghcr.io/pkorobeinikov/seeder --file Dockerfile seeder

  image:push:
    desc: Publish Docker image
    cmds:
      - docker push ghcr.io/pkorobeinikov/seeder
