version: '3'

tasks:

  doc:run:
    desc: Run documentation locally
    dir: seeder-doc
    cmds:
      - |
        docker run \
          --name seeder-doc \
          --pull always \
          --rm \
          -p 8000:8000 \
          -v ${PWD}:/docs \
          squidfunk/mkdocs-material serve --dev-addr=0.0.0.0:8000 --watch-theme

  image:build:
    desc: Build Docker image
    cmds:
      - docker build --tag ghcr.io/pkorobeinikov/seeder --file Dockerfile seeder

  image:push:
    desc: Publish Docker image
    cmds:
      - docker push ghcr.io/pkorobeinikov/seeder
