site_name: seeder
repo_url: https://github.com/petr-korobeinikov/seeder
repo_name: petr-korobeinikov/seeder
edit_uri: ""
theme:
  name: material
  features:
    - toc.integrate
    - navigation.tracking
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
nav:
  - Введение: index.md
  - Установка: install.md
  - Быстрый старт: quick-start.md
  - Туториал:
      - Postgres: tutorial/postgres.md
      - Vault: tutorial/vault.md
      - S3: tutorial/s3.md
      - Kafka: tutorial/kafka.md
  - Разработка:
      - ADR:
          - 1. Record architecture decisions: development/adr/0001-record-architecture-decisions.md
          - 2. Use strict YAML configuration format: development/adr/0002-use-strict-yaml-configuration-format.md
          - 3. Vault seeding spec: development/adr/0003-vault-seeding-spec.md
      - Roadmap: development/roadmap.md
